-- Credits to Beyond All Reason team
{
	name = "Wind Generator",
	activatewhenbuilt = true,
	buildpic = "ARMWIN.DDS",
	buildtime = 1600,
	canrepeat = false,
	collisionvolumeoffsets = "0 1 0",
	collisionvolumescales = "34 87 34",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	energycost = 175,
	energystorage = 0.5,
	explodeas = "windboom",
	footprintx = 3,
	footprintz = 3,
	health = 196,
	idleautoheal = 5,
	idletime = 1800,
	maxacc = 0,
	maxdec = 0,
	maxslope = 10,
	maxwaterdepth = 0,
	metalcost = 40,
	objectname = "Units/ARMWIN.s3o",
	script = "Units/ARMWIN.cob",
	seismicsignature = 0,
	selfdestructas = "windboom",
	sightdistance = 273,
	windgenerator = 25,
	yardmap = "ooo ooo ooo",
}
